security:
  oauth2:
#    sso:
#      loginPath:/callback
    client:
      accessTokenUri: http://localhost:8100/oauth/token
      userAuthorizationUri: http://localhost:8100/oauth/authorize
      clientId: clientAuthorizationCodeGT
      clientSecret: 123456
      registered-redirect-uri: http://localhost:9001/callback
      grant-type: authorization_code

    resource:
      userInfoUri: https://graph.facebook.com/me

#security:
#  oauth2:
#    client:
#      accessTokenUri: http://localhost:8100/oauth/token
#      userAuthorizationUri: http://localhost:8100/oauth/authorize
#      clientId: clientAuthorizationCodeGT
#      clientSecret: 123456

